apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterrole.name }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes", "ingressroutetcps"]
  verbs: ["get", "list"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes", "ingressroutetcps"]
  verbs: ["get", "list"]