apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterrole.name }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterrolebinding.name }}
roleRef:
  apiGroup: {{ .Values.rbac.clusterrolebinding.roleRef.apiGroup }}
  kind: {{ .Values.rbac.clusterrolebinding.roleRef.kind }}
  name: {{ .Values.rbac.clusterrolebinding.roleRef.name }}
subjects:
- kind: {{ .Values.rbac.clusterrolebinding.subjects.kind }}
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.namespace }}